#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 18, 2022 08:42:16 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import sqlite3 
import Card

import CardDisplayer

def display(thisCard: Card.Card):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1, _thisCard
    _top1 = root
    _w1 = CardDisplayer.CardDisplayer(_top1)
    _thisCard = thisCard
    
    _w1.textTitle.insert(END, thisCard.title)
    _w1.labelCardId.configure(text="卡片ID：" + str(thisCard.cardId))
    _w1.textContent.insert(END, thisCard.content)
    
    root.mainloop()

def buttonSaveClick(*args):
    
    conn = sqlite3.connect('d:\\NoteLiteRecords.db') 
    cur = conn.cursor()
    insertCard = f"insert into cards (title, content) values (?,?);"
    replaceCard = f"replace  into cards (cardId, title, content) values (?,?,?);"
    if _thisCard.cardId == 0:
        cur.execute(insertCard, (_w1.textTitle.get("1.0",END), _w1.textContent.get("1.0",END)))
    else:
        cur.execute(replaceCard, (_thisCard.cardId, _w1.textTitle.get("1.0",END), _w1.textContent.get("1.0",END)))
    conn.commit()