#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    May 28, 2022 08:23:43 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import Card
import CardDisplayer_support


import CardList
from DbHelper import DbHelper

def showList():
    dbHelper = DbHelper()
    global _cards
    _cards = dbHelper.readAllCards()
    
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = CardList.CardList(_top1)
    refreshList(_cards)
    
    root.mainloop()

def buttonDisplayCardClicked(*unused1):
    cardSelected = _w1.listboxCards.curselection()
    if len(cardSelected) == 0:
        return
    CardDisplayer_support.display(_cards[cardSelected[0]], cardSelected[0])

def updateList(card: Card.Card, index:int) -> int:
    newIndex = None
    if (index == None):
        _cards.append(card)
        newIndex = len(_cards) - 1
    else:
        _cards[index] = card
        newIndex = index
    refreshList(_cards)
    return newIndex

def refreshList(cards: list[Card.Card]):
    _w1.listboxCards.delete(0, END)
    for card in cards:
        _w1.listboxCards.insert(END, card.title + ":" + card.content)

def listItemDoubleClick(*unused1):
    buttonDisplayCardClicked()

def addButtonClicked(*args):
    card = Card.Card(0, "", "", "")
    CardDisplayer_support.display(card, None)
